In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import time

# Basic PyTorch Functions

## Multinomial

In [2]:
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])


## Cat

In [3]:
tensor = torch.tensor([1,2,3,4])
out =torch.cat((tensor,torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

## tril - triu

In [4]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [5]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

## masked_fill

In [6]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)== 0), float('-inf'))
out

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# transpose

In [7]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [8]:
input = torch.zeros(2,3,4)
out = input.transpose(1,2)
out.shape

torch.Size([2, 4, 3])

In [9]:
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3 , 3, bias=False)
print(linear(sample))

tensor([ 3.6336, -0.1276, -7.0701], grad_fn=<SqueezeBackward4>)


In [10]:
tensor1 = torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [11]:
embedding_layer = nn.Embedding(num_embeddings=10000, embedding_dim=300)
input_indices =torch.LongTensor([1,5,3,2])

embedded_output = embedding_layer(input_indices)
print(embedded_output.shape)

torch.Size([4, 300])


In [12]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
print(x,y,z )
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])
